services:
  postgres:
    image: postgres:16
    container_name: evaluations-db
    environment:
      POSTGRES_DB: evaluationsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  evaluations-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluations-service
    depends_on:
      - postgres

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/evaluationsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      KEYCLOAK_CLIENT_SECRET: mzjROuTev2gNJsHrSVyeNU4KF5Lgtgfe

      KEYCLOAK_SERVER_URL: "http://keycloak:8080"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KEYCLOAK_REALM: ifrn

      MINIO_SERVER_URL: "http://minio:9000"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      BUCKET_FILES_NAME: files
      BUCKET_IMAGES_NAME: images

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin123

      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - "8080:8080"
    networks:
      - classnet
      - infra
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge
  infra:
    external: true

volumes:
  pgdata:
