services:
  academic-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academic-service-local
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BUCKET_FILES_NAME: ${BUCKET_FILES_NAME}
      BUCKET_IMAGES_NAME: ${BUCKET_IMAGES_NAME}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SPRING_SERVER_URL: ${SPRING_SERVER_URL}
      SPRING_EXTERNAL_PORT: ${SPRING_EXTERNAL_PORT}
    ports:
      - "8085:8085"
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge
  infra:
    external: true

volumes:
  pgdata: