server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: "optional:dotenv:.env"

  application:
    name: Academic Service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /api/docs
    url: /v3/api-docs
    server-url: http://localhost:8080
  show-actuator: true

# Configuração global de CORS (opcional, mas útil no Swagger)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

keycloak:
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  server-url: ${KEYCLOAK_SERVER_URL}
  admin-user: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: ${KEYCLOAK_REALM}

minio:
  server-url: ${MINIO_SERVER_URL}
  admin-user: ${MINIO_ROOT_USER}
  admin-password: ${MINIO_ROOT_PASSWORD}
  bucket-files: ${BUCKET_FILES_NAME}
  bucket-images: ${BUCKET_IMAGES_NAME}