server:
  port: ${SPRING_EXTERNAL_PORT}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: "optional:dotenv:.env"

  application:
    name: Academic Service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code

            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            user-name-attribute: preferred_username
            # URL que o NAVEGADOR vai usar (fora do docker)
            #authorization-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/auth
            # URL que o BACKEND vai usar (dentro do docker)
            #token-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/token
            #jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/certs
            #user-info-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/userinfo
            issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn
      resourceserver:
        jwt:
          #jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/ifrn

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cache:
    type: redis

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/docs
    url: /v3/api-docs
    server-url: ${SPRING_SERVER_URL}
    config-url: /v3/api-docs/swagger-config
    oauth:
      client-id: swagger-ui
      use-pkce-with-authorization-code-grant: true
      scopes: openid profile email
      authorization-url: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/auth
      token-url: ${KEYCLOAK_SERVER_URL}/realms/ifrn/protocol/openid-connect/token
  show-actuator: true

# Configuração global de CORS (opcional, mas útil no Swagger)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, loggers
  endpoint:
    prometheus:
      enabled: true

keycloak:
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  server-url: ${KEYCLOAK_SERVER_URL}
  admin-user: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}

minio:
  server-url: ${MINIO_SERVER_URL}
  admin-user: ${MINIO_ROOT_USER}
  admin-password: ${MINIO_ROOT_PASSWORD}
  bucket-files: ${BUCKET_FILES_NAME}
  bucket-images: ${BUCKET_IMAGES_NAME}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}