name: Testes e Relatórios

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Dar permissão de execução ao mvnw
        run: chmod +x ./mvnw

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, testes e coverage
        run: ./mvnw clean verify

      - name: Gerar relatório Surefire HTML
        run: ./mvnw surefire-report:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: |
            target/site/surefire-report.html
            target/surefire-reports/

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Trivy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build, Scan & Push Import Service
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/academic_service:latest
          docker build -t $IMAGE_NAME .
          trivy image --exit-code 1 --severity CRITICAL $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Disparar Deploy no Easypanel
        run: |
          curl -X POST "${{ secrets.EASYPANEL_DEPLOY_URL }}"