name: Testes e Relatórios

on:
  push:
    branches: [ main, develop, test/mutation_tests ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Dar permissão de execução ao mvnw
        run: chmod +x ./mvnw

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build, testes e coverage
        run: ./mvnw clean verify

      - name: Gerar relatório Surefire HTML
        run: ./mvnw surefire-report:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: |
            target/site/surefire-report.html
            target/surefire-reports/

